name: YouTube Live Recorder

on:
  schedule:
    # هر ۵ دقیقه چک کن کانال لایو هست یا نه
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  record_live:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yt-dlp + FFmpeg
        uses: AnimMouse/setup-yt-dlp@v3
        with:
          ffmpeg: true

      - name: Check and Record YouTube Live
        run: |
          CHANNEL="https://www.youtube.com/@bigezmogestream"
          DATE=$(date +%Y-%m-%d_%H-%M-%S)
          mkdir -p recordings

          # بررسی لایو بودن کانال
          STATUS=$(yt-dlp --skip-download --print "%(is_live)s" "$CHANNEL")
          if [ "$STATUS" = "True" ]; then
            echo "Channel is live! Start recording..."
            yt-dlp --live-from-start -f best \
              -o "recordings/live_${DATE}_%(title)s.%(ext)s" \
              "$CHANNEL"
          else
            echo "Channel is not live, skipping..."
          fi

      - name: Upload recordings as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yt-live-recordings
          path: recordings/*

      - name: Upload recordings to Google Drive
        if: success()
        run: |
          for file in recordings/*; do
            rclone copy "$file" gdrive:/YouTube_Live --progress
          done
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
